variable "ec2-sg-name" {}
variable "vpc-id" {}
variable "alb-sg-id" {}
variable "lt-name" {}
variable "ami-id" {}
variable "sshkey" {}
variable "public-subnets" {}
variable "asg-name" {}
variable "tg-arn" {}
variable "asg-policy" {}
variable "cw-name" {}
variable "asg-policy-down" {}
variable "cw-scaling-down" {}