name: Generate terraform docs
on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@main
        with:
          working-dir: .
          config-file: .terraform-docs.yml
          git-push: "true"
          git-commit-message: "terraform-docs: automated action"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
