name: Generate terraform docs
on:
  - pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@main
      with:
        working-dir: .
        config-file: .terraform-docs.yml
        git-push: true
        git-push-sign-off: true
        git-commit-message: "terraform-docs: automated action"
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
