name: Generate terraform docs
on:
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Render terraform docs and push changes back to pull_request
        uses: ./
        with:
          working-dir: .
          config-file: .terraform-docs.yml

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Commit changes
        run: |
          git add .
          git commit -m "terraform-docs: automated action"

      - name: Push changes
        uses: terraform-docs/gh-actions@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branches: main
